const tr={
fa:{dir:'rtl',btn:'EN',nav_home:'خانه',nav_about:'درباره',nav_music:'موسیقی',nav_members:'اعضا',nav_contact:'تماس',about_label:'درباره ما',kicker:'',hero_a:'ما',band_name:'جیلیز ویلیز',hero_b:'یم!',hero_text:'آلترناتیو/فیوژن تشکیل شده در تهران!',listen:'گوش بده',about_btn:'درباره ما',follow:'ما را دنبال کنید',about_text:'جیلیز ویلیز از سال ۱۴۰۳ فعالیتش را شروع کرد؛ گروهی آلترناتیو/فیوژن که توسط آرین شریعت، نوازنده گیتار و خواننده، و سپهر عباسی، نوازنده ترومبون، شکل گرفت. بعدتر ماهان محمدی با ترومپت، نوید غالب با بیس و صالح خان محمدی با درامز به گروه اضافه شدند.',music_title:'کار های منتشر شده',track_1:'اولین قطعه منتشرشده جیلیز ویلیز.',track_2:'یک قطعه از دنیای شلوغ، رنگی و صمیمی گروه.',members_title:'اعضا',read_bio:'بیوگرافی',name_arian:'آرین شریعت',name_sepehr:'سپهر عباسی',name_mahan:'ماهان محمدی',name_navid:'نوید غالب',name_saleh:'صالح خان محمدی',role_arian:'گیتار / وکال',role_sepehr:'ترومبون',role_mahan:'ترومپت',role_navid:'بیس',role_saleh:'درامز',bio_arian_short:'گیتار، وکال و ایده‌های اولیه.',bio_sepehr_short:'ترومبون و رنگ‌های گرم برنجی.',bio_mahan_short:'ترومپت و خط‌های روشن.',bio_navid_short:'بیس و ستون فرکانس‌های پایین.',bio_saleh_short:'درامز و ریتم‌های پرانرژی.',bio_arian:'آرین بین ملودی‌های ساده، ریف‌های جَزی و ایده‌های عجیب زندگی می‌کند و معمولاً همان‌جا آهنگ می‌سازد.',bio_sepehr:'سپهر صدای گرم ترومبون را وارد گروه کرد؛ جایی بین هارمونی، شوخی و لحظه‌های سینمایی.',bio_mahan:'ماهان با ترومپت خط‌های روشن، تیز و پرانرژی می‌سازد؛ مثل چراغی وسط شلوغی قطعه.',bio_navid:'نوید زمینِ قطعه‌ها را نگه می‌دارد؛ فرکانس‌هایی که شاید کمتر دیده شوند، اما همه‌چیز روی آن‌ها می‌ایستد.',bio_saleh:'صالح ریتم‌ها را جمع‌وجور می‌کند، بعد با سلیقه دوباره آن‌ها را کمی به هم می‌ریزد.',contact_title:'ما را دنبال کنید'},
en:{dir:'ltr',btn:'FA',nav_home:'Home',nav_about:'About',nav_music:'Music',nav_members:'Members',nav_contact:'Contact',about_label:'About us',kicker:'From Tehran, with odd rhythms',hero_a:'We are',band_name:'Jilliz Williz',hero_b:'!',hero_text:'An alternative/fusion band formed in Tehran!',listen:'Listen',about_btn:'About us',follow:'Follow us',about_text:'Jilliz Williz started in 2024; an alternative/fusion band founded by Arian Shariat, guitarist and vocalist, and Sepehr Abbasi, trombonist. Later, Mahan Mohammadi on trumpet, Navid Ghaleb on bass, and Saleh Khan Mohammadi on drums joined the band.',music_title:'Released Works',track_1:'The first released track by Jilliz Williz.',track_2:'A track from the band’s messy, colorful and intimate world.',members_title:'Members',read_bio:'Biography',name_arian:'Arian Shariat',name_sepehr:'Sepehr Abbasi',name_mahan:'Mahan Mohammadi',name_navid:'Navid Ghaleb',name_saleh:'Saleh Khan Mohammadi',role_arian:'Guitar / Vocal',role_sepehr:'Trombone',role_mahan:'Trumpet',role_navid:'Bass',role_saleh:'Drums',bio_arian_short:'Guitar, vocals, and first ideas.',bio_sepehr_short:'Trombone and warm brass colors.',bio_mahan_short:'Trumpet and bright lines.',bio_navid_short:'Bass and the low-end foundation.',bio_saleh_short:'Drums and energetic rhythms.',bio_arian:'Arian lives somewhere between simple melodies, jazzy riffs and strange ideas; that is usually where songs happen. In Jilliz Williz, he brings the vocal and guitar parts together with a song-oriented but experimental approach.',bio_sepehr:'Sepehr brings the warm sound of trombone into the band; somewhere between harmony, humor and cinematic moments. His presence gives the songs a deep brass color and an unexpected twist.',bio_mahan:'Mahan creates bright, sharp and energetic trumpet lines; like a light in the middle of the song’s chaos. His role is to add shiny phrases and short melodic bursts to the band sound.',bio_navid:'Navid holds the ground beneath the songs; frequencies that may be less visible, but everything stands on them. His bass keeps the rhythmic body of the band steady and fluid.',bio_saleh:'Saleh gathers the rhythms together, then tastefully messes them up again. His drums push the live energy forward and keep the songs moving.',contact_title:'Follow us'}
};
let current='fa';
const btn=document.getElementById('langBtn');
function setLang(lang){current=lang;document.documentElement.lang=lang;document.documentElement.dir=tr[lang].dir;document.body.classList.toggle('en',lang==='en');btn.textContent=tr[lang].btn;document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(tr[lang][k])el.textContent=tr[lang][k]})}
btn.addEventListener('click',()=>setLang(current==='fa'?'en':'fa'));
setLang('fa');
